services:
  redis-template:
    image: redis:7
    container_name: redis-template:
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  template-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-backend
    ports:
      - "5007:5007"
    env_file:
      - .env
    volumes:
      - .:/app
      - template-logs:/app/winston
      - /app/node_modules
    depends_on:
      redis-template:
        condition: service_healthy
        
    command: pnpm run dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
volumes:
  template-logs:
