// src\enums\user.ts
/* eslint-disable no-unused-vars */
export enum USER_ROLES {
  ADMIN = 'ADMIN',
  USER = 'USER',
  OWNER = 'OWNER',
  MODERATOR = 'MODERATOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  WAITING = 'WAITING',
  PENDING = 'PENDING',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
  ARCHIVED = 'ARCHIVED',

  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  INFO = 'INFO',
}
